package scu.android.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RESOURCE.
 */
public class Resource implements java.io.Serializable {

    private Long id;
    private Long resource_id;
    private String resource_spath;
    private String resource_lpath;

    public Resource() {
    }

    public Resource(Long id) {
        this.id = id;
    }

    public Resource(Long id, Long resource_id, String resource_spath, String resource_lpath) {
        this.id = id;
        this.resource_id = resource_id;
        this.resource_spath = resource_spath;
        this.resource_lpath = resource_lpath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getResource_id() {
        return resource_id;
    }

    public void setResource_id(Long resource_id) {
        this.resource_id = resource_id;
    }

    public String getResource_spath() {
        return resource_spath;
    }

    public void setResource_spath(String resource_spath) {
        this.resource_spath = resource_spath;
    }

    public String getResource_lpath() {
        return resource_lpath;
    }

    public void setResource_lpath(String resource_lpath) {
        this.resource_lpath = resource_lpath;
    }

}
