package scu.android.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import scu.android.dao.Story;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STORY.
*/
public class StoryDao extends AbstractDao<Story, Long> {

    public static final String TABLENAME = "STORY";

    /**
     * Properties of entity Story.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property S_id = new Property(1, Long.class, "s_id", false, "S_ID");
        public final static Property S_text = new Property(2, String.class, "s_text", false, "S_TEXT");
        public final static Property S_user = new Property(3, Long.class, "s_user", false, "S_USER");
        public final static Property S_title = new Property(4, String.class, "s_title", false, "S_TITLE");
        public final static Property Created_time = new Property(5, Long.class, "created_time", false, "CREATED_TIME");
    };

    private DaoSession daoSession;

    private Query<Story> user_StoryListQuery;

    public StoryDao(DaoConfig config) {
        super(config);
    }
    
    public StoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'STORY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'S_ID' INTEGER," + // 1: s_id
                "'S_TEXT' TEXT," + // 2: s_text
                "'S_USER' INTEGER," + // 3: s_user
                "'S_TITLE' TEXT," + // 4: s_title
                "'CREATED_TIME' INTEGER);"); // 5: created_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Story entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long s_id = entity.getS_id();
        if (s_id != null) {
            stmt.bindLong(2, s_id);
        }
 
        String s_text = entity.getS_text();
        if (s_text != null) {
            stmt.bindString(3, s_text);
        }
 
        Long s_user = entity.getS_user();
        if (s_user != null) {
            stmt.bindLong(4, s_user);
        }
 
        String s_title = entity.getS_title();
        if (s_title != null) {
            stmt.bindString(5, s_title);
        }
 
        Long created_time = entity.getCreated_time();
        if (created_time != null) {
            stmt.bindLong(6, created_time);
        }
    }

    @Override
    protected void attachEntity(Story entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Story readEntity(Cursor cursor, int offset) {
        Story entity = new Story( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // s_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // s_text
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // s_user
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // s_title
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // created_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Story entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setS_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setS_text(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setS_user(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setS_title(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCreated_time(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Story entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Story entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "storyList" to-many relationship of User. */
    public List<Story> _queryUser_StoryList(Long s_user) {
        synchronized (this) {
            if (user_StoryListQuery == null) {
                QueryBuilder<Story> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.S_user.eq(null));
                user_StoryListQuery = queryBuilder.build();
            }
        }
        Query<Story> query = user_StoryListQuery.forCurrentThread();
        query.setParameter(0, s_user);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM STORY T");
            builder.append(" LEFT JOIN USER T0 ON T.'S_USER'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Story loadCurrentDeep(Cursor cursor, boolean lock) {
        Story entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setUser(user);

        return entity;    
    }

    public Story loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Story> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Story> list = new ArrayList<Story>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Story> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Story> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
